### PR TITLE
Add `AssertWpErrorTypeSpecifyingExtension` / `AssertNotWpErrorTypeSpecifyingExtension`

### LINKED ISSUE #30: Treat assertNotWPError() and assertWPError() as type-narrowing functions
In the WordPress core test suite the following assertion methods are available:

* `$this->assertNotWPError()`
* `$this->assertWPError()`

It would be great if this extension treated these methods as type-narrowing functions, so the following code would not throw an error in PHPStan:

```php
$terms = wp_get_post_terms( $post_id, $taxonomy );
$this->assertNotWPError( $terms );
$this->assertCount( 0, $terms );
```

Currently this triggers the following error because `$terms` is assumed to be `array|WP_Error` on the last line.

```
[phpstan] Parameter #2 $haystack of method PHPUnit\Framework\Assert::assertCount() expects Countable|iterable, array|WP_Error given.
```

### PR DESCRIPTION
**Pull request by swissspidy**
Might need a bit of help with the implementation & tests, but I think this should cover the basics.

Fixes #30

### CODE REVIEW

**Comment by johnbillion** [comment]
This might be possible with the new docblock-based assertions instead: https://phpstan.org/blog/phpstan-1-9-0-with-phpdoc-asserts-list-type

**Comment by johnbillion** [comment]
Although that would mean bumping the minimum PHPStan requirement up to the latest.

**Comment by swissspidy** [comment]
@johnbillion That would mean having to add the docblocks in core, right?

**Comment by szepeviktor** [comment]
I'm not a maintainer.
I can write code only for myself.

**Comment by szepeviktor** [comment]
...okay let's release v1.2.0 after this PR

**Comment by johnbillion** [comment]
> That would mean having to add the docblocks in core, right?

The https://github.com/php-stubs/wordpress-stubs/ library has a node visitor that allows additional tags to be added to the docblocks for function stubs, but AFAICT the methods in the test suite aren't generated as part of those stubs, so for now I think this type specifying extension makes the most sense actually 👍

**Comment by swissspidy** [comment]
Just marking as ready for review in the hopes of triggering tests to run... Can't get them to work locally somehow.

**Comment by szepeviktor** [comment]
Importing `WP_UnitTestCase_Base` may be missing from tests.

**Comment by herndlm** [comment]
hey, I still have my phpstorm open from yesterday basically. I can quickly check if I see something :)

**Comment by swissspidy** [comment]
Oh, did not expect this to be merged 😅 

There's probably something silly I missed with these extensions. Again, I haven't been able to run the tests locally for some reason, so it was just copy & paste

@herndlm Any help is much appreciated, thank you!

**Comment by herndlm** [comment]
Viktor's merge finger was too fast :)

**Comment by szepeviktor** [comment]
> Viktor's merge finger was too fast :)

CI was not running in this PR

Please continue in a new PR fixing this one.

**Pull request merged**
