### PR TITLE
Test *ERROR*

### PR DESCRIPTION
**Pull request by szepeviktor**
@johnbillion

### CODE REVIEW

**Comment by johnbillion** [comment]
Playground which works as expected: https://phpstan.org/r/d7b65195-af14-40cf-a216-9b70bdda21c0

**Comment by szepeviktor** [comment]
@ondrejmirtes Could you help us why it fails in our simple PHPUnit test environment but it works in the playground?

**Comment by ondrejmirtes** [comment]
You can't write test code like that. Functions need to be loaded. What I do most often is to write a class and test code inside that (because classes can be autoloaded automatically). If I need to use functions, I need to write test code in anonymous functions, like in this file: https://github.com/phpstan/phpstan-src/blob/master/tests/PHPStan/Analyser/data/generics.php

File in this format can be safely `require`'d.

**Comment by szepeviktor** [comment]
Thank you for solving this.

**Pull request closed without merging**
