### PR TITLE
Add Support my work section

### PR DESCRIPTION
**Pull request by szepeviktor**
👀
https://github.com/szepeviktor/phpstan-wordpress/blob/szepeviktor-patch-1/README.md#support-my-work
@adamlaki There seems to be a color difference and this heart does not beat :(

What if we add the same ids/classes -> then GitHub's CSS will work on our svg too?

### CODE REVIEW

**Comment by adamlaki** [comment]
Viktor,

you asked this via e-mail; why didn't you continue the discussion over there?

Please, don't give half the information. If a color does not match, what color is it?

What kind of animation do you want, just on the hover state (like the button)?

**Comment by szepeviktor** [comment]
> Please, don't give half the information. If a color does not match, what color is it?

I'm sorry.
This PR fixes the color. https://github.com/szepeviktor/.github/pull/1
Could you approve it?

> What kind of animation do you want, just on the hover state (like the button)?

Yes, hover-only animation.
Is that possible in SVG?
This button is used in README-s.

**Comment by adamlaki** [comment]
I've approved it, looks good.

Yes, in theory, it is possible. I will make the addition soon.

**Comment by adamlaki** [comment]
I don't understand where the color diff is coming from; it is correct in the file that I sent you.

**Comment by szepeviktor** [comment]
I've added some SVG features and optimization.

```xml
    <rect width="92" height="28" ...
    <path fill="#BF3989" ...
    <text ...
```

**Pull request merged**
