### PR TITLE
Run tests on lowest deps also

### PR DESCRIPTION
**Pull request by szepeviktor**
@herndlm Here we go 🐎 

From https://github.com/szepeviktor/phpstan-wordpress/pull/122#issuecomment-1309363724

### CODE REVIEW

**Comment by szepeviktor** [comment]
>   - Locking wp-coding-standards/wpcs (2.1.0)

**Comment by herndlm** [comment]
yep, the phpcs errors can be fixed by upgrading the non direct dependency `wp-coding-standards/wpcs` from 2.1.0 to 2.3.0  but then some other CS errors show up, but it's a step forward

**Comment by szepeviktor** [comment]
> upgrading the non direct dependency `wp-coding-standards/wpcs`

Done.

**Comment by herndlm** [comment]
`composer require --dev szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset:^0.6.1 automattic/phpcs-neutron-standard:^1.7` fixes all phpcs errors but one

**Comment by szepeviktor** [comment]
Let's just ignore CS.
I'm not willing to fiddle with my CS for hours.

**Comment by herndlm** [comment]
the dev deps in general are not important at all for the lowest deps IMO. annoying that they get downgraded

**Comment by herndlm** [comment]
a good pragmatical solution might be to run the lowest tests with just e.g. `composer update --prefer-lowest --prefer-stable php-stubs/wordpress-stubs phpstan/phpstan`

**Comment by herndlm** [comment]
looks like you're determined to fix it 🎉
for the stub-dependency I think I can build you some conditional tests. e.g. one mysql2date for WP 5 and one for WP 6 or so, or just lock them to WP 6

**Comment by szepeviktor** [comment]
@herndlm Dev deps fixed!

How to handle inconsistent WP types?

**Comment by szepeviktor** [comment]
AFAIK WP 6.0 introduced meaningful types. Up to 5.0 types were mainly ignored.

**Comment by szepeviktor** [comment]
You can't cook a tasty soup of mud!!

**Comment by herndlm** [comment]
hehe, I wanted to suggest to wrap some tests maybe in something like
```php
if (InstalledVersions::satisfies(new VersionParser(), 'php-stubs/wordpress-stubs', '^5.0')) {
            yield from $this->gatherAssertTypes(__DIR__ . '/data/wp_error_parameter.php');
        }
```

but locking the stubs should be fine, right. lower phpstan version is the most interesting thing most likely :)

**Comment by herndlm** [comment]
I think this makes sense, thx Viktor

**Comment by szepeviktor** [comment]
Today's German lesson had a new word: _Alptraum_ - that is something I do not want!

**Pull request merged**
