### PR TITLE
Add TEMPLATEPATH, STYLESHEETPATH, and WP_DEFAULT_THEME constants

### PR DESCRIPTION
**Pull request by westonruter**
See [`wp_templating_constants()`](https://github.com/WordPress/wordpress-develop/blob/dbbc9bcf98787fd77fd920df84cc9bbc69974b0a/src/wp-includes/default-constants.php#L387-L420)

### CODE REVIEW

**Comment by szepeviktor** [comment]
I'd like to encourage core function usage.
Plugins rarely read these constants. So I do not merge this one.

**Comment by szepeviktor** [comment]
@westonruter Please see this disgusting package: https://github.com/php-stubs/wordpress-globals

**Comment by westonruter** [comment]
I'm not sure I would characterize usage as rare: https://wpdirectory.net/search/01GXJ8KH4ZGP4T39CTX92Q7YWZ

**Comment by szepeviktor** [comment]
Yes you are right.
I say using globals has no part in a software. But we have WordPress.
This is all I can offer.

If I would be a WordPress promoter, all core globals would be part of this project.

**Comment by westonruter** [comment]
I guess I misunderstood your motivations for this project.

**Comment by szepeviktor** [comment]
I've realized I should support the WordPress ecosystem even I cannot tolerate it code quality.
Please see the _What to avoid_ list https://github.com/szepeviktor/starter-plugin#what-to-avoid

**Pull request merged**
