### PR TITLE
Switch from boostrap stubs to scanned wordpress dir

### PR DESCRIPTION
**Pull request by herndlm**
Closes https://github.com/szepeviktor/phpstan-wordpress/issues/99
Just playing around with an improvement idea.

had to temporarily limit the phpstan upper version for testing because currently 1.6.0 seems to be not fully compatible yet (HookDocsRuleTest).

### CODE REVIEW

**Comment by herndlm** [comment]
I think this would work and improves performance quite a bit. The only downsides I see so far are
- Viktors stub file is not used anymore :/
- the WordPress checkout is bigger than the stub file (~60M or so)

**Comment by herndlm** [comment]
fyi CI was green here, but as Ondrej mentioned this would need bleedingEdge and I think it is preferred to fix stub/bootstrap parsing performance, see issue for details

**Comment by herndlm** [comment]
good idea, I'll look into the core problem in phpstan itself first and think about this again then

**Comment by szepeviktor** [comment]
I think 101% of code developed for WordPress is written in PHP4-style, so they could use the speedup of `scanDirectories:`.

**Pull request closed without merging**
